### ISSUE TITLE
How to pip install this?

### ISSUE THREAD

**Issue by vikadis** [stryngs/officeTasks#1]
I had a dev work on a company project and use this module/ library. I am having issues importing the library and installing the library. 

I have been using `pip install git+<GIT CLONE URL>`

My error message is: ERROR: File "setup.py" not found for legacy project git+https://github.com/stryngs/officeTasks.git.

**Comment by stryngs** [comment]
pip install -----------> officeTasks-1.4.6.tar.gz

**Comment by stryngs** [comment]
Did that work for you @vikadis ?

**Comment by stryngs** [comment]
I will assume it did.  Closing this issue out.
